package com.ted.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.greendao.ted.greendaodemo.TradeDate;

import com.ted.greendao.TradeDateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tradeDateDaoConfig;

    private final TradeDateDao tradeDateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tradeDateDaoConfig = daoConfigMap.get(TradeDateDao.class).clone();
        tradeDateDaoConfig.initIdentityScope(type);

        tradeDateDao = new TradeDateDao(tradeDateDaoConfig, this);

        registerDao(TradeDate.class, tradeDateDao);
    }
    
    public void clear() {
        tradeDateDaoConfig.clearIdentityScope();
    }

    public TradeDateDao getTradeDateDao() {
        return tradeDateDao;
    }

}
